url: https://thanhdaoky.github.io
baseurl: /thanhdaoky.github.io/

# Site settings
title: Welcome to my blog!
email: daokythanh.343@gmail.com
description: "Hey, nice to meet you!"


# Team names, titles and social links
people:
- name: Thanh Dao Ky
  pic: 1
  position: Java Intern
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/daokythanh
  - title: github
    url: http://github.com/thanhdaoky

# Postal address (add as many lines as necessary)
address:
  - line: #
  - line: #

# Build settings
markdown: kramdown
permalink: pretty
